kramdown: 
  toc_levels: '2,3'

# Custom
default-bg-image: falcon.jpg

nav:
  - title: Home
    url: /

  - title: About
    url: /

  - title: Contact
    url: /

  - title: GitHub
    url: https://github.com/danbraj

nav-overlay: false
footer-text: 'project: danbraj'